//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_items
    {
        public int ID { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> item_total { get; set; }
    }
}
