//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int ID { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<int> sale { get; set; }
        public Nullable<int> sale_percentage { get; set; }
    }
}
