//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> phone { get; set; }
        public string address_country { get; set; }
        public string address_city { get; set; }
        public string address_street { get; set; }
    }
}
